#!/bin/bash
baseURL="https://www.nobelprize.org/nomination/archive";
cd temphtmldir/ 
prize=Chemistry
for ((year=1901;year<=1971;year++))
	do
	links=(`wget --user-agent="Mozilla Firefox 48.0" -O - "https://www.nobelprize.org/nomination/archive/list.php?year=1901&prize=2" | egrep -o "show\.php.id=[0-9]+"`)
	for link in $links
	do
	    id=$(echo $link |sed 's/.*id=\([0-9]*\)/\1/')
	    wget -o download.log --user-agent="Mozilla Firefox 48.0" -O - "$baseURL/$link" > $prize-$year-$id.html
	done
done
